version: 2.1

jobs:
    build:
        docker:
            -   image: cimg/php:8.1
                environment:
                    DATABASE_URL: "mysql://test:test@127.0.0.1:3306/main?serverVersion=8.0.32&charset=utf8mb4"
            -   image: cimg/mysql:8.0
                environment:
                    MYSQL_DATABASE: main
                    MYSQL_PASSWOrD: test
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_USER: test
        steps:
            - checkout
            -   run:
                    name: Install dependencies
                    command: composer install
            -   run:
                    name: Waiting for MySQL to be ready
                    command: |
                        for i in `seq 1 10`;
                        do
                          nc -z 127.0.0.1 3306 && echo Success && exit 0
                          echo -n .
                          sleep 1
                        done
                        echo Failed waiting for MySQL && exit 1
            -   run:
                    name: Run tests
                    command: php -v
#                    command: bin/phpunit
