version: 2.1

jobs:
    build:
        docker:
            -   image: cimg/php:8.1
            -   image: cimg/mysql:8.0
        steps:
            - checkout
            -   run:
                    name: Install dependencies
                    command: composer install
            -   run:
                    name: Run tests
                    command: bin/phpunit
